Remove deprecated code
valiton/harbourmaster-sso-drupal8-plugin pull request #4
Opened 2019-12-02 13:33 UTC by chrfritsch

2020-01-14 14:51 UTC, alexpott requested changes
Also I think that we could remove jQuery.ready() see https://www.drupal.org/project/drupal/issues/3086375

2020-01-14 14:51 UTC, alexpott commented on harbourmaster.install
> +  \Drupal::messenger()->addMessage(
addWarning() and remove the last arg.

2020-01-14 16:16 UTC, chrfritsch commented
> Also I think that we could remove jQuery.ready() see https://www.drupal.org/project/drupal/issues/3086375

TBH I am afraid to do this change since I am not able to test this module.

2020-01-15 10:10 UTC, alexpott commented
> TBH I am afraid to do this change since I am not able to test this module.

Fair enough. I don't think jQuery is going to be removed in D9.

2020-01-16 08:41 UTC, dbosen approved these changes
lgtm

2020-01-16 08:42 UTC, merged